### ISSUE TITLE
UPDATE readme.md : keybind!  changing option

### ISSUE THREAD

**Issue by omaru-ok** [willswats/mpv-youtube-search#2]
at readme.md [keybinds](https://github.com/willswats/mpv-youtube-search#keybindings)

how to chnange those option .  with input.conf . since my mpv can't read driect from sciprt's  key's  :(  
_p.s = i m dumb to block all kyebinds rather than what i use _

and also i would like to change those option from ALT+S to somethign etc.   :)  im the guy from reddit named omaru_kun

**Comment by omaru-ok** [comment]
just liek thsi 
Ctrl+S script-message open_search  # alredy done from conf scipt

**Comment by willswats** [comment]
I [added](https://github.com/willswats/mpv-youtube-search/commit/683969008c0bbf0374d2d186e9c913cb50759b69) `input.conf` configuration to the [README](https://github.com/willswats/mpv-youtube-search/blob/main/README.md). The names of the keybindings may change again in the future, but I will keep the [README](https://github.com/willswats/mpv-youtube-search/blob/main/README.md) up to date. Does that solve your issue?

**Comment by omaru-ok** [comment]
> 

ayo yepp :D <3
